export default [
    {
      id: 'q1',
      text: 'What is AngularJS?',
      answers: [
        'A JavaScript framework for building web applications',
        'A CSS framework for styling web pages',
        'A database management system',
        'A programming language',
        'A web server',
      ],
    },
    {
      id: 'q2',
      text: 'What is a directive in AngularJS?',
      answers: [
        'A marker on a DOM element that tells AngularJS to attach a behavior to that element',
        'A type of service used to fetch data',
        'A method to handle HTTP requests',
        'A way to create a new module',
        'A tool for debugging AngularJS applications',
      ],
    },
    {
      id: 'q3',
      text: 'What is a module in AngularJS?',
      answers: [
        'A container for the different parts of an application',
        'A function that performs a specific task',
        'A file that contains all the application code',
        'A built-in AngularJS service',
        'A CSS preprocessor',
      ],
    },
    {
      id: 'q4',
      text: 'How do you create a new module in AngularJS?',
      answers: [
        'Using the angular.module method',
        'Using the angular.createModule method',
        'Using the ngModule directive',
        'Using the module.directive method',
        'Using the angular.newModule method',
      ],
    },
    {
      id: 'q5',
      text: 'What is the purpose of a controller in AngularJS?',
      answers: [
        'To control the data of an AngularJS application',
        'To define the styles of an AngularJS application',
        'To handle HTTP requests',
        'To create custom directives',
        'To manage dependencies in an AngularJS application',
      ],
    },
    {
      id: 'q6',
      text: 'What is two-way data binding in AngularJS?',
      answers: [
        'A synchronization between the model and the view',
        'A way to bind data from two different sources',
        'A method to handle form validation',
        'A technique for optimizing performance',
        'A tool for debugging data changes',
      ],
    },
    {
      id: 'q7',
      text: 'Which directive is used to define an AngularJS application?',
      answers: [
        'ng-app',
        'ng-init',
        'ng-model',
        'ng-controller',
        'ng-directive',
      ],
    },
    {
      id: 'q8',
      text: 'How do you define a controller in AngularJS?',
      answers: [
        'Using the ng-controller directive',
        'Using the ng-init directive',
        'Using the ng-app directive',
        'Using the ng-model directive',
        'Using the ng-directive directive',
      ],
    },
    {
      id: 'q9',
      text: 'What is a service in AngularJS?',
      answers: [
        'A reusable singleton object that can be used across the application',
        'A method to define a controller',
        'A function to handle events',
        'A tool for debugging applications',
        'A type of directive',
      ],
    },
    {
      id: 'q10',
      text: 'How do you create a service in AngularJS?',
      answers: [
        'Using the angular.service method',
        'Using the angular.module method',
        'Using the angular.directive method',
        'Using the angular.factory method',
        'Using the angular.controller method',
      ],
    },
    {
      id: 'q11',
      text: 'What is dependency injection in AngularJS?',
      answers: [
        'A design pattern that makes it easy to inject dependencies into components',
        'A method to fetch data from a server',
        'A way to bind data to the view',
        'A technique for handling events',
        'A tool for optimizing performance',
      ],
    },
    {
      id: 'q12',
      text: 'Which directive is used to bind the value of an input field to a variable in AngularJS?',
      answers: [
        'ng-model',
        'ng-bind',
        'ng-controller',
        'ng-app',
        'ng-init',
      ],
    },
    {
      id: 'q13',
      text: 'What is the purpose of the $scope object in AngularJS?',
      answers: [
        'To bind the view and the controller',
        'To handle HTTP requests',
        'To define custom directives',
        'To manage modules',
        'To create services',
      ],
    },
    {
      id: 'q14',
      text: 'Which directive is used to repeat a set of HTML elements in AngularJS?',
      answers: [
        'ng-repeat',
        'ng-for',
        'ng-loop',
        'ng-each',
        'ng-iterate',
      ],
    },
    {
      id: 'q15',
      text: 'Which service is used to make HTTP requests in AngularJS?',
      answers: [
        '$http',
        '$resource',
        '$web',
        '$ajax',
        '$fetch',
      ],
    },
    {
      id: 'q16',
      text: 'What is a filter in AngularJS?',
      answers: [
        'A way to format data displayed to the user',
        'A method to handle events',
        'A function to define a controller',
        'A tool for debugging applications',
        'A type of directive',
      ],
    },
    {
      id: 'q17',
      text: 'How do you include an external JavaScript file in an AngularJS application?',
      answers: [
        'Using the script tag',
        'Using the ng-include directive',
        'Using the ng-script directive',
        'Using the include attribute',
        'Using the external tag',
      ],
    },
    {
      id: 'q18',
      text: 'Which directive is used to conditionally include/exclude an element in AngularJS?',
      answers: [
        'ng-if',
        'ng-show',
        'ng-hide',
        'ng-include',
        'ng-switch',
      ],
    },
    {
      id: 'q19',
      text: 'What is the purpose of the ng-show directive in AngularJS?',
      answers: [
        'To display an element based on a condition',
        'To hide an element based on a condition',
        'To bind data to the view',
        'To repeat a set of elements',
        'To handle events in the view',
      ],
    },
    {
      id: 'q20',
      text: 'Which directive is used to execute an expression when an element is clicked in AngularJS?',
      answers: [
        'ng-click',
        'ng-change',
        'ng-mouseover',
        'ng-keypress',
        'ng-dblclick',
      ],
    },
    {
      id: 'q21',
      text: 'What is the purpose of the ng-init directive in AngularJS?',
      answers: [
        'To initialize data for an application',
        'To define a controller',
        'To create a new module',
        'To fetch data from a server',
        'To apply a filter to data',
      ],
    },
    {
      id: 'q22',
      text: 'How do you handle form submission in AngularJS?',
      answers: [
        'Using the ng-submit directive',
        'Using the ng-form directive',
        'Using the ng-submit attribute',
        'Using the ng-action directive',
        'Using the ng-post directive',
      ],
    },
    {
      id: 'q23',
      text: 'What is the purpose of the ng-model directive in AngularJS?',
      answers: [
        'To bind the value of an HTML control to a variable',
        'To define a new module',
        'To create a custom directive',
        'To handle HTTP requests',
        'To format data displayed to the user',
      ],
    },
    {
      id: 'q24',
      text: 'Which AngularJS directive binds an element’s attribute value to an expression?',
      answers: [
        'ng-bind',
        'ng-model',
        'ng-init',
        'ng-controller',
        'ng-include',
      ],
    },
    {
      id: 'q25',
      text: 'What is the purpose of the ng-controller directive in AngularJS?',
      answers: [
        'To define the controller for an AngularJS application',
        'To create a new module',
        'To initialize data for an application',
        'To fetch data from a server',
        'To apply a filter to data',
      ],
    },
];
