export default [
    {
      id: 'q1',
      text: 'What does CSS stand for?',
      answers: [
        'Cascading Style Sheets',
        'Computer Style Sheets',
        'Creative Style Sheets',
        'Colorful Style Sheets',
        'Custom Style Sheets',
      ],
    },
    {
      id: 'q2',
      text: 'Which HTML attribute is used to define inline styles?',
      answers: [
        'style',
        'class',
        'id',
        'css',
        'inline',
      ],
    },
    {
      id: 'q3',
      text: 'Which CSS property is used to change the text color of an element?',
      answers: [
        'color',
        'text-color',
        'font-color',
        'fgcolor',
        'foreground-color',
      ],
    },
    {
      id: 'q4',
      text: 'Which CSS property is used to change the background color of an element?',
      answers: [
        'background-color',
        'bgcolor',
        'background',
        'color',
        'background-image',
      ],
    },
    {
      id: 'q5',
      text: 'Which CSS property is used to change the font of an element?',
      answers: [
        'font-family',
        'font-style',
        'font-weight',
        'font',
        'text-font',
      ],
    },
    {
      id: 'q6',
      text: 'How do you add a background image in CSS?',
      answers: [
        'background-image: url(image.jpg);',
        'background-color: image.jpg;',
        'background: image.jpg;',
        'bg-image: image.jpg;',
        'image-background: url(image.jpg);',
      ],
    },
    {
      id: 'q7',
      text: 'Which CSS property is used to control the spacing between elements?',
      answers: [
        'margin',
        'padding',
        'spacing',
        'border',
        'gap',
      ],
    },
    {
      id: 'q8',
      text: 'Which CSS property is used to control the spacing within an element?',
      answers: [
        'padding',
        'margin',
        'spacing',
        'border',
        'gap',
      ],
    },
    {
      id: 'q9',
      text: 'Which CSS property is used to change the size of the text?',
      answers: [
        'font-size',
        'text-size',
        'font-weight',
        'text-style',
        'text-transform',
      ],
    },
    {
      id: 'q10',
      text: 'Which CSS property is used to make the text bold?',
      answers: [
        'font-weight',
        'font-style',
        'font-bold',
        'text-weight',
        'text-bold',
      ],
    },
    {
      id: 'q11',
      text: 'Which CSS property is used to align text to the center?',
      answers: [
        'text-align: center;',
        'text-center: align;',
        'align: center;',
        'text-align: middle;',
        'text-center: center;',
      ],
    },
    {
      id: 'q12',
      text: 'How do you select an element with id "header" in CSS?',
      answers: [
        '#header',
        '.header',
        'header',
        'id=header',
        '[header]',
      ],
    },
    {
      id: 'q13',
      text: 'How do you select all elements with class "container" in CSS?',
      answers: [
        '.container',
        '#container',
        'container',
        '[class=container]',
        'class=container',
      ],
    },
    {
      id: 'q14',
      text: 'Which CSS property is used to create space between the border and content of an element?',
      answers: [
        'padding',
        'margin',
        'spacing',
        'border-spacing',
        'gap',
      ],
    },
    {
      id: 'q15',
      text: 'Which CSS property is used to set the width of an element?',
      answers: [
        'width',
        'height',
        'size',
        'length',
        'dimension',
      ],
    },
    {
      id: 'q16',
      text: 'Which CSS property is used to set the height of an element?',
      answers: [
        'height',
        'width',
        'size',
        'length',
        'dimension',
      ],
    },
    {
      id: 'q17',
      text: 'Which CSS property is used to set the maximum width of an element?',
      answers: [
        'max-width',
        'width',
        'min-width',
        'max-size',
        'max-dimension',
      ],
    },
    {
      id: 'q18',
      text: 'Which CSS property is used to set the minimum height of an element?',
      answers: [
        'min-height',
        'height',
        'max-height',
        'min-size',
        'min-dimension',
      ],
    },
    {
      id: 'q19',
      text: 'Which CSS property is used to add shadows to text?',
      answers: [
        'text-shadow',
        'shadow-text',
        'text-shadowing',
        'text-outline',
        'text-decor',
      ],
    },
    {
      id: 'q20',
      text: 'Which CSS property is used to control the order of flexible items?',
      answers: [
        'order',
        'flex-order',
        'item-order',
        'flex-direction',
        'order-index',
      ],
    },
    {
      id: 'q21',
      text: 'Which CSS property is used to change the cursor type?',
      answers: [
        'cursor',
        'pointer',
        'mouse',
        'cursor-type',
        'point',
      ],
    },
    {
      id: 'q22',
      text: 'Which CSS property is used to set the color of a border?',
      answers: [
        'border-color',
        'border-style',
        'border-width',
        'border',
        'color-border',
      ],
    },
    {
      id: 'q23',
      text: 'Which CSS property is used to create rounded corners?',
      answers: [
        'border-radius',
        'corner-radius',
        'border-corner',
        'border-round',
        'round-border',
      ],
    },
    {
      id: 'q24',
      text: 'Which CSS property is used to specify the stack order of elements?',
      answers: [
        'z-index',
        'order',
        'stack',
        'position',
        'layer',
      ],
    },
    {
      id: 'q25',
      text: 'Which CSS property is used to specify whether an element is visible or hidden?',
      answers: [
        'visibility',
        'display',
        'opacity',
        'show',
        'hide',
      ],
    },
    {
      id: 'q26',
      text: 'Which CSS property is used to specify the background color of an element?',
      answers: [
        'background-color',
        'color',
        'bg-color',
        'background',
        'background-image',
      ],
    },
    {
      id: 'q27',
      text: 'Which CSS property is used to specify the font size of an element?',
      answers: [
        'font-size',
        'text-size',
        'font-style',
        'text-style',
        'font-weight',
      ],
    },
    {
      id: 'q28',
      text: 'Which CSS property is used to specify the font style of an element?',
      answers: [
        'font-style',
        'font-size',
        'text-size',
        'text-style',
        'font-weight',
      ],
    },
    {
      id: 'q29',
      text: 'Which CSS property is used to specify the font weight of an element?',
      answers: [
        'font-weight',
        'font-size',
        'text-size',
        'text-style',
        'font-style',
      ],
    },
    {
      id: 'q30',
      text: 'Which CSS property is used to specify the line height of an element?',
      answers: [
        'line-height',
        'line-size',
        'height-line',
        'line-width',
        'line-style',
      ],
    },
    {
      id: 'q31',
      text: 'Which CSS property is used to specify the letter spacing of text?',
      answers: [
        'letter-spacing',
        'text-spacing',
        'font-spacing',
        'letter-space',
        'font-space',
      ],
    },
    {
      id: 'q32',
      text: 'Which CSS property is used to specify the word spacing of text?',
      answers: [
        'word-spacing',
        'text-spacing',
        'font-spacing',
        'word-space',
        'font-space',
      ],
    },
    {
      id: 'q33',
      text: 'Which CSS property is used to transform text to uppercase?',
      answers: [
        'text-transform: uppercase;',
        'text-case: uppercase;',
        'text-style: uppercase;',
        'transform: uppercase;',
        'font-case: uppercase;',
      ],
    },
    {
      id: 'q34',
      text: 'Which CSS property is used to specify the white space behavior of an element?',
      answers: [
        'white-space',
        'text-space',
        'font-space',
        'space-white',
        'space-text',
      ],
    },
]