export default [
    {
      id: 'q1',
      text: 'What does HTML stand for?',
      answers: [
        'HyperText Markup Language',
        'HyperText Markdown Language',
        'HighText Markup Language',
        'HyperTool Markup Language',
        'HighText Markdown Language',
      ],
    },
    {
      id: 'q2',
      text: 'Which HTML element is used to define the title of a document?',
      answers: [
        '<title>',
        '<head>',
        '<meta>',
        '<header>',
        '<body>',
      ],
    },
    {
      id: 'q3',
      text: 'What is the purpose of the <head> element in HTML?',
      answers: [
        'It contains meta-information about the document.',
        'It contains the main content of the document.',
        'It creates a heading for the document.',
        'It defines the footer of the document.',
        'It links external scripts to the document.',
      ],
    },
    {
      id: 'q4',
      text: 'Which HTML element is used to create a hyperlink?',
      answers: [
        '<a>',
        '<link>',
        '<href>',
        '<hyperlink>',
        '<nav>',
      ],
    },
    {
      id: 'q5',
      text: 'Which attribute is used to specify the URL in a hyperlink?',
      answers: [
        'href',
        'src',
        'link',
        'url',
        'target',
      ],
    },
    {
      id: 'q6',
      text: 'Which HTML element is used to define an unordered list?',
      answers: [
        '<ul>',
        '<ol>',
        '<li>',
        '<list>',
        '<dl>',
      ],
    },
    {
      id: 'q7',
      text: 'Which HTML element is used to define a list item?',
      answers: [
        '<li>',
        '<ul>',
        '<ol>',
        '<item>',
        '<dl>',
      ],
    },
    {
      id: 'q8',
      text: 'What is the correct HTML element for inserting a line break?',
      answers: [
        '<br>',
        '<break>',
        '<lb>',
        '<line>',
        '<hr>',
      ],
    },
    {
      id: 'q9',
      text: 'Which attribute is used to specify an image in HTML?',
      answers: [
        'src',
        'href',
        'link',
        'url',
        'alt',
      ],
    },
    {
      id: 'q10',
      text: 'Which HTML element is used to create a table?',
      answers: [
        '<table>',
        '<tr>',
        '<td>',
        '<th>',
        '<tbody>',
      ],
    },
    {
      id: 'q11',
      text: 'Which HTML element is used to define a table row?',
      answers: [
        '<tr>',
        '<td>',
        '<th>',
        '<table>',
        '<tbody>',
      ],
    },
    {
      id: 'q12',
      text: 'Which HTML element is used to define a table cell?',
      answers: [
        '<td>',
        '<tr>',
        '<th>',
        '<table>',
        '<tbody>',
      ],
    },
    {
      id: 'q13',
      text: 'Which HTML element is used to define a table header?',
      answers: [
        '<th>',
        '<td>',
        '<tr>',
        '<table>',
        '<thead>',
      ],
    },
    {
      id: 'q14',
      text: 'What is the correct HTML element for the largest heading?',
      answers: [
        '<h1>',
        '<h2>',
        '<h3>',
        '<h4>',
        '<h5>',
      ],
    },
    {
      id: 'q15',
      text: 'Which attribute is used to provide an alternative text for an image, if the image cannot be displayed?',
      answers: [
        'alt',
        'title',
        'src',
        'href',
        'description',
      ],
    },
    {
      id: 'q16',
      text: 'Which HTML element is used to define emphasized text?',
      answers: [
        '<em>',
        '<i>',
        '<strong>',
        '<b>',
        '<u>',
      ],
    },
    {
      id: 'q17',
      text: 'Which HTML element is used to define important text?',
      answers: [
        '<strong>',
        '<b>',
        '<em>',
        '<i>',
        '<u>',
      ],
    },
    {
      id: 'q18',
      text: 'Which attribute is used to specify the language of the HTML document?',
      answers: [
        'lang',
        'xml:lang',
        'dir',
        'lang-code',
        'locale',
      ],
    },
    {
      id: 'q19',
      text: 'What is the correct HTML element for inserting a horizontal rule?',
      answers: [
        '<hr>',
        '<br>',
        '<line>',
        '<break>',
        '<rule>',
      ],
    },
    {
      id: 'q20',
      text: 'Which HTML element is used to define a section in a document?',
      answers: [
        '<section>',
        '<div>',
        '<article>',
        '<header>',
        '<footer>',
      ],
    },
    {
      id: 'q21',
      text: 'Which HTML element is used to define a footer for a document or section?',
      answers: [
        '<footer>',
        '<section>',
        '<div>',
        '<article>',
        '<nav>',
      ],
    },
    {
      id: 'q22',
      text: 'Which HTML element is used to define navigation links?',
      answers: [
        '<nav>',
        '<header>',
        '<footer>',
        '<aside>',
        '<section>',
      ],
    },
    {
      id: 'q23',
      text: 'Which HTML element is used to define a section that is quoted from another source?',
      answers: [
        '<blockquote>',
        '<quote>',
        '<q>',
        '<cite>',
        '<quotation>',
      ],
    },
    {
      id: 'q24',
      text: 'Which attribute is used to specify a unique identifier for an HTML element?',
      answers: [
        'id',
        'class',
        'name',
        'key',
        'data-id',
      ],
    },
    {
      id: 'q25',
      text: 'Which attribute is used to group elements by class in HTML?',
      answers: [
        'class',
        'id',
        'name',
        'data-class',
        'group',
      ],
    },
    {
      id: 'q26',
      text: 'What is the correct HTML element for playing video files?',
      answers: [
        '<video>',
        '<media>',
        '<movie>',
        '<audio>',
        '<embed>',
      ],
    },
    {
      id: 'q27',
      text: 'What is the correct HTML element for playing audio files?',
      answers: [
        '<audio>',
        '<sound>',
        '<music>',
        '<media>',
        '<embed>',
      ],
    },
    {
      id: 'q28',
      text: 'Which HTML element is used to embed an external page within an HTML document?',
      answers: [
        '<iframe>',
        '<frame>',
        '<embed>',
        '<object>',
        '<import>',
      ],
    },
    {
      id: 'q29',
      text: 'Which attribute is used to specify the URL of an iframe?',
      answers: [
        'src',
        'href',
        'link',
        'url',
        'target',
      ],
    },
    {
      id: 'q30',
      text: 'Which attribute specifies the width of an iframe?',
      answers: [
        'width',
        'height',
        'size',
        'length',
        'dimension',
      ],
    },
    {
      id: 'q31',
      text: 'Which attribute specifies the height of an iframe?',
      answers: [
        'height',
        'width',
        'size',
        'length',
        'dimension',
      ],
    },
    {
      id: 'q32',
      text: 'What is the correct HTML element for inserting an inline frame?',
      answers: [
        '<iframe>',
        '<frame>',
        '<embed>',
        '<object>',
        '<import>',
      ],
    },
    {
      id: 'q33',
      text: 'Which attribute is used to open a link in a new tab or window?',
      answers: [
        'target="_blank"',
        'target="_new"',
        'rel="noopener"',
        'window="new"',
        'tab="new"',
      ],
    },
    {
      id: 'q34',
      text: 'Which HTML element is used to define a client-side script?',
      answers: [
        '<script>',
        '<code>',
        '<style>',
        '<link>',
        '<client>',
      ],
    },
    {
      id: 'q35',
      text: 'Which attribute is used to specify the type of script in the <script> element?',
      answers: [
        'type',
        'src',
        'language',
        'code',
        'script-type',
      ],
    },
    {
      id: 'q36',
      text: 'Which attribute is used to specify the source of an external script in the <script> element?',
      answers: [
        'src',
        'type',
        'language',
        'code',
        'script-source',
      ],
    }
]  