export default [
    {
      id: 'q1',
      text: 'What does "var" stand for in JavaScript?',
      answers: [
        'Variable',
        'Variant',
        'Various',
        'Variation',
        'Variety',
      ],
    },
    {
      id: 'q2',
      text: 'Which company developed JavaScript?',
      answers: [
        'Netscape',
        'Microsoft',
        'Google',
        'Apple',
        'IBM',
      ],
    },
    {
      id: 'q3',
      text: 'Which keyword is used to declare a variable in JavaScript?',
      answers: [
        'var',
        'let',
        'const',
        'declare',
        'define',
      ],
    },
    {
      id: 'q4',
      text: 'Which method is used to write HTML output in JavaScript?',
      answers: [
        'document.write()',
        'console.log()',
        'alert()',
        'print()',
        'write()',
      ],
    },
    {
      id: 'q5',
      text: 'Which JavaScript method is used to convert a JSON string into an object?',
      answers: [
        'JSON.parse()',
        'JSON.stringify()',
        'JSON.objectify()',
        'JSON.toObject()',
        'JSON.convert()',
      ],
    },
    {
      id: 'q6',
      text: 'Which method is used to create a new array by calling a function for every array element?',
      answers: [
        'map()',
        'forEach()',
        'filter()',
        'reduce()',
        'sort()',
      ],
    },
    {
      id: 'q7',
      text: 'Which keyword is used to define a constant in JavaScript?',
      answers: [
        'const',
        'let',
        'var',
        'constant',
        'define',
      ],
    },
    {
      id: 'q8',
      text: 'Which method removes the last element from an array and returns that element?',
      answers: [
        'pop()',
        'push()',
        'shift()',
        'unshift()',
        'splice()',
      ],
    },
    {
      id: 'q9',
      text: 'Which method adds one or more elements to the end of an array and returns the new length?',
      answers: [
        'push()',
        'pop()',
        'shift()',
        'unshift()',
        'concat()',
      ],
    },
    {
      id: 'q10',
      text: 'Which event occurs when the user clicks on an HTML element?',
      answers: [
        'onclick',
        'onchange',
        'onmouseover',
        'onmouseout',
        'onkeydown',
      ],
    },
    {
      id: 'q11',
      text: 'Which function is used to execute a piece of code after a specified delay?',
      answers: [
        'setTimeout()',
        'setInterval()',
        'clearTimeout()',
        'clearInterval()',
        'delay()',
      ],
    },
    {
      id: 'q12',
      text: 'Which method returns the character at a specified index in a string?',
      answers: [
        'charAt()',
        'charCodeAt()',
        'indexOf()',
        'substring()',
        'slice()',
      ],
    },
    {
      id: 'q13',
      text: 'Which operator is used to assign a value to a variable?',
      answers: [
        '=',
        '==',
        '===',
        '!=',
        '!==',
      ],
    },
    {
      id: 'q14',
      text: 'Which operator is used to compare both value and type without type conversion?',
      answers: [
        '===',
        '==',
        '=',
        '!=',
        '!==',
      ],
    },
    {
      id: 'q15',
      text: 'Which JavaScript method is used to remove the whitespace from both ends of a string?',
      answers: [
        'trim()',
        'slice()',
        'split()',
        'replace()',
        'substring()',
      ],
    },
    {
      id: 'q16',
      text: 'Which method calls a function once for each element in an array?',
      answers: [
        'forEach()',
        'map()',
        'filter()',
        'reduce()',
        'every()',
      ],
    },
    {
      id: 'q17',
      text: 'Which method is used to combine two or more arrays?',
      answers: [
        'concat()',
        'join()',
        'push()',
        'merge()',
        'combine()',
      ],
    },
    {
      id: 'q18',
      text: 'Which object represents the eventual completion or failure of an asynchronous operation?',
      answers: [
        'Promise',
        'Async',
        'Callback',
        'Event',
        'Await',
      ],
    },
    {
      id: 'q19',
      text: 'Which method is used to convert an array to a string?',
      answers: [
        'join()',
        'toString()',
        'concat()',
        'slice()',
        'split()',
      ],
    },
    {
      id: 'q20',
      text: 'Which keyword is used to handle exceptions in JavaScript?',
      answers: [
        'try',
        'catch',
        'finally',
        'throw',
        'error',
      ],
    },
    {
      id: 'q21',
      text: 'Which method is used to return a new array with all elements that pass a test?',
      answers: [
        'filter()',
        'map()',
        'forEach()',
        'reduce()',
        'find()',
      ],
    },
    {
      id: 'q22',
      text: 'Which operator is used to check if two values are not equal?',
      answers: [
        '!=',
        '==',
        '=',
        '!==',
        '===',
      ],
    },
    {
      id: 'q23',
      text: 'Which method is used to sort the elements of an array?',
      answers: [
        'sort()',
        'order()',
        'arrange()',
        'lineUp()',
        'rank()',
      ],
    },
    {
      id: 'q24',
      text: 'Which keyword is used to create a class in JavaScript?',
      answers: [
        'class',
        'constructor',
        'function',
        'object',
        'prototype',
      ],
    },
    {
      id: 'q25',
      text: 'Which method is used to find the first element that satisfies a test?',
      answers: [
        'find()',
        'filter()',
        'map()',
        'forEach()',
        'every()',
      ],
    },
    {
      id: 'q26',
      text: 'Which method is used to add new elements to the beginning of an array?',
      answers: [
        'unshift()',
        'shift()',
        'push()',
        'pop()',
        'concat()',
      ],
    },
    {
      id: 'q27',
      text: 'Which keyword is used to import modules in JavaScript?',
      answers: [
        'import',
        'include',
        'require',
        'fetch',
        'get',
      ],
    },
    {
      id: 'q28',
      text: 'Which method is used to execute a function for each element in an array?',
      answers: [
        'forEach()',
        'map()',
        'filter()',
        'reduce()',
        'every()',
      ],
    },
    {
      id: 'q29',
      text: 'Which method is used to join two or more arrays?',
      answers: [
        'concat()',
        'join()',
        'merge()',
        'combine()',
        'append()',
      ],
    },
    {
      id: 'q30',
      text: 'Which method is used to extract a part of a string?',
      answers: [
        'substring()',
        'substr()',
        'slice()',
        'split()',
        'extract()',
      ],
    },
];
